// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiK3k_SuRkUBhydfH6_Q0v3eyGGPR01ho',
    appId: '1:891928193926:web:fba6c356ee3e3505e45a07',
    messagingSenderId: '891928193926',
    projectId: 'fruit-hub-52852',
    authDomain: 'fruit-hub-52852.firebaseapp.com',
    storageBucket: 'fruit-hub-52852.firebasestorage.app',
    measurementId: 'G-ZW0P48YRRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKyk45Tb6oYuZWIn4x-_D7iYszAqSGW6I',
    appId: '1:891928193926:android:5f9bb8895d2f5f72e45a07',
    messagingSenderId: '891928193926',
    projectId: 'fruit-hub-52852',
    storageBucket: 'fruit-hub-52852.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA5Ltysrb3ul0-evL2F7sgieZZ_3o-UFI',
    appId: '1:891928193926:ios:9c311353703e99ade45a07',
    messagingSenderId: '891928193926',
    projectId: 'fruit-hub-52852',
    storageBucket: 'fruit-hub-52852.firebasestorage.app',
    iosBundleId: 'com.example.ecomerceMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA5Ltysrb3ul0-evL2F7sgieZZ_3o-UFI',
    appId: '1:891928193926:ios:9c311353703e99ade45a07',
    messagingSenderId: '891928193926',
    projectId: 'fruit-hub-52852',
    storageBucket: 'fruit-hub-52852.firebasestorage.app',
    iosBundleId: 'com.example.ecomerceMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiK3k_SuRkUBhydfH6_Q0v3eyGGPR01ho',
    appId: '1:891928193926:web:128bfd0853341f21e45a07',
    messagingSenderId: '891928193926',
    projectId: 'fruit-hub-52852',
    authDomain: 'fruit-hub-52852.firebaseapp.com',
    storageBucket: 'fruit-hub-52852.firebasestorage.app',
    measurementId: 'G-8S5Z6RJKT1',
  );
}
